graph LR
    mcm[MobiCoMonkey]
    mcm --- a[Configuration Reader]
    mcm --- b[Contextual Scenario Generator]
    mcm --- c[App Manager]
    mcm --- d[Executor]
    mcm --- e[Log Analyzer]
    mcm --- f[Fatal Execution Watcher]